require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/db/schema.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'bin/*'
    - 'db/migrate/20160906113948_add_devise_to_users.rb'

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
